#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Accepts four parameters:
#+    The path of file and IP of server to be transferred.
#+    username dat scp conects wit % path to SSH prv8 key dat scp uses.

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
