#!/usr/bin/env bash
# string that Pings an IP address
# and also received as an argument 5 times.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
