#!/usr/bin/env bash
# Bash script that configures a server to the below requirements
# Nginx running, n listening on port 80 of all server’s active IPv4 IPs

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
