#!/usr/bin/env bash
# Bash script that displays infinity/beyond indefinitel
# With a sleep 2 in between each iteration

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
