#!/usr/bin/env bash
# you will need to get Apache to run on the container
# return a page contni Hello Holberton when querying the root.

echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
