#!/usr/bin/env bash
# SSH client configuration should use private key ~/.ssh/school
# SSH client config must refuse to authenticate using a password
Host *
      PasswordAuthentication no
      IdentifyFile ~/.ssh/school
